[build-system]
requires = ["setuptools"] #, "setuptools-scm"]
build-backend = "setuptools.build_meta"

#[tool.setuptools_scm]
#version_file = "dbt_pipeline_utils/_version.py"

[project]
name = "dbt_pipeline_utils"
authors = [
    {name = "Brenda Gutman", email="brenda.gutman@vumc.org"}
]
description = ""
readme = "README.md"
requires-python = ">3.10"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = ["pandas",
                "PyYAML",
                "python-dotenv",
                "rich"
                ]

dynamic = ["version"]

[tool.setuptools_scm]
version_file = "src/dbt_pipeline_utils/_version.py"

[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)

[project.scripts]
generate_models_yml = "dbt_pipeline_utils.p_utils.actions.generate_models_yml:main"
generate_sources_yml = "dbt_pipeline_utils.p_utils.actions.generate_sources_yml:main"
generate_sql_models = "dbt_pipeline_utils.p_utils.actions.generate_sql_models:main"
generate_models_yml_from_release_asset = "dbt_pipeline_utils.p_utils.actions.generate_models_yml_from_release_asset:main"
list_release_assets = "dbt_pipeline_utils.p_utils.actions.list_release_assets:main"
extract_release_artifact_file = "dbt_pipeline_utils.p_utils.actions.extract_release_artifact_file:main"