[build-system]
requires = ["setuptools"] #, "setuptools-scm"]
build-backend = "setuptools.build_meta"

#[tool.setuptools_scm]
#version_file = "dbt_pipeline_utils/_version.py"

[project]
name = "dbt_pipeline_utils"
authors = [
    {name = "Brenda Gutman", email="brenda.gutman@vumc.org"}
]
description = ""
readme = "README.md"
requires-python = ">3.10"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = ["rich",
                "duckdb",
                "sqlparse",
                "protobuf==5.29.5", # dbt core and adapters require specific versions, do check GH advisory db: CVE-2025-4565
                "locutus @ git+https://github.com/NIH-NCPI/locutus@v2.2.9"
                ]

dynamic = ["version"]

[tool.setuptools_scm]
version_file = "src/dbt_pipeline_utils/_version.py"

[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)

[tool.setuptools.package-data]
dbt_pipeline_utils = ["data/static/files/**", "data/static/macros/**"]

[project.scripts]
generate_pipeline = "dbt_pipeline_utils.p_utils.actions.generate_pipeline:main"
generate_dbt_project = "dbt_pipeline_utils.p_utils.actions.generate_dbt_project:main"